import { prisma } from "../src/lib/db";

const weeks = [
  { week: 1, fruit: "Mohnsamen", fruitDe: "Mohnsamen", fruitEn: "Poppy seed", fruitFa: "دانه خشخاش", sizeCm: 0.01, weightG: 0, milestoneDe: "Dein Körper bereitet sich auf den Eisprung vor", milestoneEn: "Your body prepares for ovulation", milestoneFa: "بدن شما برای تخمک‌گذاری آماده می‌شود", tipDe: "Beginne mit Folsäure, wenn du es noch nicht tust", tipEn: "Start taking folic acid if you haven't already", tipFa: "اگر هنوز شروع نکرده‌ای، اسید فولیک مصرف کن" },
  { week: 2, fruit: "Mohnsamen", fruitDe: "Mohnsamen", fruitEn: "Poppy seed", fruitFa: "دانه خشخاش", sizeCm: 0.02, weightG: 0, milestoneDe: "Der Eisprung findet statt – die Befruchtung kann erfolgen", milestoneEn: "Ovulation occurs – fertilization can happen", milestoneFa: "تخمک‌گذاری انجام می‌شود – لقاح می‌تواند اتفاق بیفتد", tipDe: "Achte auf eine ausgewogene Ernährung mit viel Gemüse", tipEn: "Eat a balanced diet with plenty of vegetables", tipFa: "به یک رژیم متعادل با سبزیجات فراوان توجه کن" },
  { week: 3, fruit: "Stecknadelkopf", fruitDe: "Stecknadelkopf", fruitEn: "Pinhead", fruitFa: "سری سوزن", sizeCm: 0.1, weightG: 0, milestoneDe: "Die Zelle teilt sich – das Leben beginnt", milestoneEn: "The cell divides – life begins", milestoneFa: "سلول تقسیم می‌شود – زندگی آغاز می‌شود", tipDe: "Vermeide Alkohol und Rauchen ab jetzt komplett", tipEn: "Avoid alcohol and smoking completely from now on", tipFa: "از همین حالا الکل و سیگار را کاملاً کنار بگذار" },
  { week: 4, fruit: "Mohnsamen", fruitDe: "Mohnsamen", fruitEn: "Poppy seed", fruitFa: "دانه خشخاش", sizeCm: 0.1, weightG: 0, milestoneDe: "Der Embryo nistet sich in der Gebärmutter ein", milestoneEn: "The embryo implants in the uterus", milestoneFa: "جنین در رحم لانه‌گزینی می‌کند", tipDe: "Deine Periode bleibt aus – Zeit für einen Schwangerschaftstest", tipEn: "Your period is late – time for a pregnancy test", tipFa: "پریودت عقب افتاده – وقت تست بارداری است" },
  { week: 5, fruit: "Apfelsamen", fruitDe: "Apfelsamen", fruitEn: "Apple seed", fruitFa: "دانه سیب", sizeCm: 0.3, weightG: 0, milestoneDe: "Das Herz beginnt zu schlagen!", milestoneEn: "The heart starts beating!", milestoneFa: "قلب شروع به تپیدن می‌کند!", tipDe: "Übelkeit kann auftreten – iss kleine, häufige Mahlzeiten", tipEn: "Nausea may occur – eat small, frequent meals", tipFa: "ممکن است حالت تهوع داشته باشی – وعده‌های کوچک و مکرر بخور" },
  { week: 6, fruit: "Erbse", fruitDe: "Erbse", fruitEn: "Pea", fruitFa: "نخود", sizeCm: 0.6, weightG: 0, milestoneDe: "Gehirn und Rückenmark beginnen sich zu bilden", milestoneEn: "Brain and spinal cord begin to form", milestoneFa: "مغز و نخاع شروع به شکل‌گیری می‌کنند", tipDe: "Trinke ausreichend Wasser – mindestens 2 Liter täglich", tipEn: "Drink plenty of water – at least 2 liters daily", tipFa: "به اندازه کافی آب بنوش – حداقل ۲ لیتر در روز" },
  { week: 7, fruit: "Blaubeere", fruitDe: "Blaubeere", fruitEn: "Blueberry", fruitFa: "زغال‌اخته", sizeCm: 1.3, weightG: 0, milestoneDe: "Arme und Beine beginnen zu wachsen", milestoneEn: "Arms and legs begin to grow", milestoneFa: "دست‌ها و پاها شروع به رشد می‌کنند", tipDe: "Vitamin B6 kann gegen Übelkeit helfen", tipEn: "Vitamin B6 can help with nausea", tipFa: "ویتامین B6 می‌تواند به کاهش تهوع کمک کند" },
  { week: 8, fruit: "Himbeere", fruitDe: "Himbeere", fruitEn: "Raspberry", fruitFa: "تمشک", sizeCm: 1.6, weightG: 1, milestoneDe: "Alle wichtigen Organe sind angelegt", milestoneEn: "All major organs have formed", milestoneFa: "همه اندام‌های اصلی شکل گرفته‌اند", tipDe: "Vereinbare deinen ersten Vorsorgetermin beim Frauenarzt", tipEn: "Schedule your first prenatal appointment", tipFa: "اولین ویزیت بارداری را با پزشک هماهنگ کن" },
  { week: 9, fruit: "Kirsche", fruitDe: "Kirsche", fruitEn: "Cherry", fruitFa: "گیلاس", sizeCm: 2.3, weightG: 2, milestoneDe: "Finger und Zehen sind vollständig getrennt", milestoneEn: "Fingers and toes are fully separated", milestoneFa: "انگشتان دست و پا کاملاً از هم جدا شده‌اند", tipDe: "Sanfte Bewegung wie Schwimmen oder Spazierengehen tut gut", tipEn: "Gentle exercise like swimming or walking is good", tipFa: "ورزش ملایم مثل شنا یا پیاده‌روی مفید است" },
  { week: 10, fruit: "Pflaume", fruitDe: "Pflaume", fruitEn: "Plum", fruitFa: "آلو", sizeCm: 3.1, weightG: 4, milestoneDe: "Das Baby kann seinen Mund öffnen und schließen", milestoneEn: "The baby can open and close its mouth", milestoneFa: "نوزاد می‌تواند دهان خود را باز و بسته کند", tipDe: "Eisenreiche Lebensmittel unterstützen die Blutbildung", tipEn: "Iron-rich foods support blood formation", tipFa: "غذاهای غنی از آهن به خون‌سازی کمک می‌کنند" },
  { week: 11, fruit: "Feige", fruitDe: "Feige", fruitEn: "Fig", fruitFa: "انجیر", sizeCm: 4.1, weightG: 7, milestoneDe: "Die Genitalien beginnen sich zu entwickeln", milestoneEn: "Genitals begin to develop", milestoneFa: "اندام تناسلی شروع به رشد می‌کند", tipDe: "Gönn dir ausreichend Schlaf – dein Körper arbeitet hart", tipEn: "Get enough sleep – your body is working hard", tipFa: "خواب کافی داشته باش – بدنت سخت کار می‌کند" },
  { week: 12, fruit: "Limette", fruitDe: "Limette", fruitEn: "Lime", fruitFa: "لیمو", sizeCm: 5.4, weightG: 14, milestoneDe: "Das Baby hat einen Greifreflex entwickelt", milestoneEn: "The baby has developed a grasp reflex", milestoneFa: "نوزاد رفلکس گرفتن را توسعه داده است", tipDe: "Das Risiko einer Fehlgeburt sinkt jetzt deutlich", tipEn: "The risk of miscarriage drops significantly now", tipFa: "خطر سقط جنین اکنون به طور قابل توجهی کاهش می‌یابد" },
  { week: 13, fruit: "Pfirsich", fruitDe: "Pfirsich", fruitEn: "Peach", fruitFa: "هلو", sizeCm: 7.4, weightG: 23, milestoneDe: "Das Baby kann seinen Daumen lutschen", milestoneEn: "The baby can suck its thumb", milestoneFa: "نوزاد می‌تواند انگشت شست خود را بمکد", tipDe: "Jetzt ist ein guter Zeitpunkt, um deine Ernährung umzustellen", tipEn: "Now is a good time to adjust your diet", tipFa: "الان زمان خوبی است تا رژیم غذایی خود را تنظیم کنی" },
  { week: 14, fruit: "Zitrone", fruitDe: "Zitrone", fruitEn: "Lemon", fruitFa: "لیمو", sizeCm: 8.7, weightG: 43, milestoneDe: "Das Baby beginnt, Fruchtwasser zu schlucken", milestoneEn: "The baby starts swallowing amniotic fluid", milestoneFa: "نوزاد شروع به بلع مایع آمنیوتیک می‌کند", tipDe: "Kalziumreiche Nahrung unterstützt den Knochenaufbau", tipEn: "Calcium-rich foods support bone development", tipFa: "غذاهای غنی از کلسیم به رشد استخوان کمک می‌کنند" },
  { week: 15, fruit: "Apfel", fruitDe: "Apfel", fruitEn: "Apple", fruitFa: "سیب", sizeCm: 10.1, weightG: 70, milestoneDe: "Das Baby kann Licht wahrnehmen", milestoneEn: "The baby can perceive light", milestoneFa: "نوزاد می‌تواند نور را درک کند", tipDe: "Trinke weiterhin ausreichend und bewege dich regelmäßig", tipEn: "Keep drinking enough and exercise regularly", tipFa: "به نوشیدن آب کافی و ورزش منظم ادامه بده" },
  { week: 16, fruit: "Avocado", fruitDe: "Avocado", fruitEn: "Avocado", fruitFa: "آووکادو", sizeCm: 11.6, weightG: 100, milestoneDe: "Das Baby kann seinen Kopf bewegen", milestoneEn: "The baby can move its head", milestoneFa: "نوزاد می‌تواند سر خود را حرکت دهد", tipDe: "Du könntest jetzt erste Kindsbewegungen spüren", tipEn: "You might feel the first baby movements now", tipFa: "ممکن است اولین حرکات جنین را حس کنی" },
  { week: 17, fruit: "Birne", fruitDe: "Birne", fruitEn: "Pear", fruitFa: "گلابی", sizeCm: 13, weightG: 140, milestoneDe: "Das Baby beginnt, Fettgewebe aufzubauen", milestoneEn: "The baby starts building fat tissue", milestoneFa: "نوزاد شروع به ساخت بافت چربی می‌کند", tipDe: "Magnesium kann Wadenkrämpfen vorbeugen", tipEn: "Magnesium can prevent leg cramps", tipFa: "منیزیم می‌تواند از گرفتگی عضلات پا جلوگیری کند" },
  { week: 18, fruit: "Paprika", fruitDe: "Paprika", fruitEn: "Bell pepper", fruitFa: "فلفل دلمه‌ای", sizeCm: 14.2, weightG: 190, milestoneDe: "Das Baby kann gähnen und Schluckauf haben", milestoneEn: "The baby can yawn and get hiccups", milestoneFa: "نوزاد می‌تواند خمیازه بکشد و سکسکه داشته باشد", tipDe: "Achte auf eine gute Körperhaltung – der Bauch wächst", tipEn: "Watch your posture – your belly is growing", tipFa: "به وضعیت بدنی خود توجه کن – شکم در حال رشد است" },
  { week: 19, fruit: "Mango", fruitDe: "Mango", fruitEn: "Mango", fruitFa: "انبه", sizeCm: 15.3, weightG: 240, milestoneDe: "Die Haut wird durch Lanugohaare geschützt", milestoneEn: "The skin is protected by lanugo hair", milestoneFa: "پوست توسط موهای کرکی محافظت می‌شود", tipDe: "Vitamin D ist jetzt besonders wichtig für Knochen", tipEn: "Vitamin D is especially important for bones now", tipFa: "ویتامین D اکنون برای استخوان‌ها بسیار مهم است" },
  { week: 20, fruit: "Banane", fruitDe: "Banane", fruitEn: "Banana", fruitFa: "موز", sizeCm: 16.5, weightG: 300, milestoneDe: "Das Baby kann hören – es reagiert auf Geräusche", milestoneEn: "The baby can hear – it reacts to sounds", milestoneFa: "نوزاد می‌شنود – به صداها واکنش نشان می‌دهد", tipDe: "Sprich und singe für dein Baby – es erkennt deine Stimme", tipEn: "Talk and sing to your baby – it recognizes your voice", tipFa: "با نوزادت صحبت کن و آواز بخوان – صدای تو را می‌شناسد" },
  { week: 21, fruit: "Karotte", fruitDe: "Karotte", fruitEn: "Carrot", fruitFa: "هویج", sizeCm: 26.7, weightG: 360, milestoneDe: "Das Baby schluckt und verdaut Fruchtwasser", milestoneEn: "The baby swallows and digests amniotic fluid", milestoneFa: "نوزاد مایع آمنیوتیک را می‌بلعد و هضم می‌کند", tipDe: "Eisenmangel ist jetzt häufig – lass deine Werte checken", tipEn: "Iron deficiency is common – get your levels checked", tipFa: "کمبود آهن شایع است – سطح آن را بررسی کن" },
  { week: 22, fruit: "Kokosnuss", fruitDe: "Kokosnuss", fruitEn: "Coconut", fruitFa: "نارگیل", sizeCm: 27.8, weightG: 430, milestoneDe: "Die Augenbrauen und Wimpern sind sichtbar", milestoneEn: "Eyebrows and eyelashes are visible", milestoneFa: "ابروها و مژه‌ها قابل مشاهده هستند", tipDe: "Schlaf auf der linken Seite für bessere Durchblutung", tipEn: "Sleep on your left side for better circulation", tipFa: "برای گردش خون بهتر به پهلوی چپ بخواب" },
  { week: 23, fruit: "Grapefruit", fruitDe: "Grapefruit", fruitEn: "Grapefruit", fruitFa: "گریپ‌فروت", sizeCm: 28.9, weightG: 500, milestoneDe: "Das Baby hat Schlaf- und Wachphasen", milestoneEn: "The baby has sleep and wake cycles", milestoneFa: "نوزاد چرخه‌های خواب و بیداری دارد", tipDe: "Trinke weiterhin viel – Fruchtwasser wird ständig erneuert", tipEn: "Keep drinking – amniotic fluid is constantly renewed", tipFa: "به نوشیدن آب ادامه بده – مایع آمنیوتیک دائماً بازسازی می‌شود" },
  { week: 24, fruit: "Maiskolben", fruitDe: "Maiskolben", fruitEn: "Ear of corn", fruitFa: "ذرت", sizeCm: 30, weightG: 600, milestoneDe: "Die Lungenbläschen beginnen sich zu bilden", milestoneEn: "The alveoli in the lungs begin to form", milestoneFa: "کیسه‌های هوایی ریه شروع به شکل‌گیری می‌کنند", tipDe: "Ab jetzt ist das Baby außerhalb der Gebärmutter überlebensfähig", tipEn: "From now on, the baby could survive outside the womb", tipFa: "از این به بعد نوزاد می‌تواند خارج از رحم زنده بماند" },
  { week: 25, fruit: "Kohlrabi", fruitDe: "Kohlrabi", fruitEn: "Rutabaga", fruitFa: "شلغم", sizeCm: 34.6, weightG: 660, milestoneDe: "Das Baby kann Grimassen schneiden", milestoneEn: "The baby can make facial expressions", milestoneFa: "نوزاد می‌تواند ادا و اطوار درآورد", tipDe: "Sodbrennen kann auftreten – iss kleinere Portionen", tipEn: "Heartburn may occur – eat smaller portions", tipFa: "ممکن است سوزش سر دل داشته باشی – وعده‌های کوچک‌تر بخور" },
  { week: 26, fruit: "Zucchini", fruitDe: "Zucchini", fruitEn: "Zucchini", fruitFa: "کدو سبز", sizeCm: 35.6, weightG: 760, milestoneDe: "Die Augen öffnen sich zum ersten Mal", milestoneEn: "The eyes open for the first time", milestoneFa: "چشم‌ها برای اولین بار باز می‌شوند", tipDe: "Schwangerschaftsstreifen können auftreten – eincremen hilft", tipEn: "Stretch marks may appear – moisturizing helps", tipFa: "ممکن است ترک‌های بارداری ظاهر شوند – مرطوب‌کننده کمک می‌کند" },
  { week: 27, fruit: "Blumenkohl", fruitDe: "Blumenkohl", fruitEn: "Cauliflower", fruitFa: "گل کلم", sizeCm: 36.6, weightG: 875, milestoneDe: "Das Baby kann träumen (REM-Schlaf)", milestoneEn: "The baby can dream (REM sleep)", milestoneFa: "نوزاد می‌تواند رویا ببیند (خواب REM)", tipDe: "Beginne mit der Vorbereitung des Kreißsaals", tipEn: "Start preparing for the delivery room", tipFa: "آماده‌سازی برای اتاق زایمان را شروع کن" },
  { week: 28, fruit: "Aubergine", fruitDe: "Aubergine", fruitEn: "Eggplant", fruitFa: "بادمجان", sizeCm: 37.6, weightG: 1000, milestoneDe: "Das Baby kann blinzeln", milestoneEn: "The baby can blink", milestoneFa: "نوزاد می‌تواند پلک بزند", tipDe: "Ab jetzt alle zwei Wochen zur Vorsorgeuntersuchung", tipEn: "From now on, prenatal checkups every two weeks", tipFa: "از این به بعد هر دو هفته یکبار معاینه بارداری" },
  { week: 29, fruit: "Butternut-Kürbis", fruitDe: "Butternut-Kürbis", fruitEn: "Butternut squash", fruitFa: "کدو حلوایی", sizeCm: 38.6, weightG: 1150, milestoneDe: "Das Baby dreht sich möglicherweise mit dem Kopf nach unten", milestoneEn: "The baby may turn head-down", milestoneFa: "نوزاد ممکن است سر را به سمت پایین بچرخاند", tipDe: "Rückenschmerzen sind normal – Wärme und Bewegung helfen", tipEn: "Back pain is normal – heat and exercise help", tipFa: "کمردرد طبیعی است – گرما و ورزش کمک می‌کند" },
  { week: 30, fruit: "Kohl", fruitDe: "Kohl", fruitEn: "Cabbage", fruitFa: "کلم", sizeCm: 39.9, weightG: 1310, milestoneDe: "Das Baby kann seine Temperatur regulieren", milestoneEn: "The baby can regulate its temperature", milestoneFa: "نوزاد می‌تواند دمای خود را تنظیم کند", tipDe: "Pack deine Krankenhaustasche – es könnte früher losgehen", tipEn: "Pack your hospital bag – it could start early", tipFa: "کیف بیمارستان را ببند – ممکن است زودتر شروع شود" },
  { week: 31, fruit: "Kokosnuss", fruitDe: "Kokosnuss", fruitEn: "Coconut", fruitFa: "نارگیل", sizeCm: 41.1, weightG: 1500, milestoneDe: "Das Baby kann zwischen hell und dunkel unterscheiden", milestoneEn: "The baby can distinguish light from dark", milestoneFa: "نوزاد می‌تواند روشنایی را از تاریکی تشخیص دهد", tipDe: "Schlafmangel jetzt häufig – ruhe dich aus, wann immer du kannst", tipEn: "Sleep deprivation is common – rest whenever you can", tipFa: "کمبود خواب شایع است – هر وقت می‌توانی استراحت کن" },
  { week: 32, fruit: "Honigmelone", fruitDe: "Honigmelone", fruitEn: "Honeydew melon", fruitFa: "خربزه", sizeCm: 42.3, weightG: 1700, milestoneDe: "Die Fingernägel sind vollständig ausgebildet", milestoneEn: "Fingernails are fully formed", milestoneFa: "ناخن‌های دست کاملاً شکل گرفته‌اند", tipDe: "Übe Atemtechniken für die Geburt", tipEn: "Practice breathing techniques for birth", tipFa: "تکنیک‌های تنفس برای زایمان را تمرین کن" },
  { week: 33, fruit: "Ananas", fruitDe: "Ananas", fruitEn: "Pineapple", fruitFa: "آناناس", sizeCm: 43.7, weightG: 1900, milestoneDe: "Das Immunsystem des Babys entwickelt sich", milestoneEn: "The baby's immune system is developing", milestoneFa: "سیستم ایمنی نوزاد در حال توسعه است", tipDe: "Jetzt wöchentlich zum Frauenarzt", tipEn: "Weekly checkups from now on", tipFa: "از این به بعد هفته‌ای یکبار به پزشک مراجعه کن" },
  { week: 34, fruit: "Melone", fruitDe: "Melone", fruitEn: "Melon", fruitFa: "طالبی", sizeCm: 45, weightG: 2100, milestoneDe: "Das Baby kann seine Augen koordinieren", milestoneEn: "The baby can coordinate its eyes", milestoneFa: "نوزاد می‌تواند چشم‌های خود را هماهنگ کند", tipDe: "Senkwehen können jetzt auftreten – das Baby rutscht tiefer", tipEn: "Braxton Hicks contractions may occur", tipFa: "ممکن است انقباضات براکستون هیکس رخ دهد" },
  { week: 35, fruit: "Honigmelone", fruitDe: "Honigmelone", fruitEn: "Honeydew", fruitFa: "خربزه", sizeCm: 46.2, weightG: 2400, milestoneDe: "Die Lungen sind fast vollständig ausgereift", milestoneEn: "The lungs are almost fully mature", milestoneFa: "ریه‌ها تقریباً کاملاً بالغ شده‌اند", tipDe: "Bereite dich mental auf die Geburt vor – Atemübungen helfen", tipEn: "Prepare mentally for birth – breathing exercises help", tipFa: "از نظر ذهنی برای زایمان آماده شو – تمرینات تنفسی کمک می‌کند" },
  { week: 36, fruit: "Kopfsalat", fruitDe: "Kopfsalat", fruitEn: "Romaine lettuce", fruitFa: "کاهو", sizeCm: 47.4, weightG: 2600, milestoneDe: "Das Baby hat einen festen Schlaf-Wach-Rhythmus", milestoneEn: "The baby has a stable sleep-wake rhythm", milestoneFa: "نوزاد ریتم ثابت خواب و بیداری دارد", tipDe: "Die Geburt kann jederzeit beginnen – bleib entspannt", tipEn: "Birth could start anytime – stay relaxed", tipFa: "زایمان می‌تواند هر لحظه شروع شود – آرام باش" },
  { week: 37, fruit: "Wassermelone (mini)", fruitDe: "Wassermelone (mini)", fruitEn: "Watermelon (mini)", fruitFa: "هندوانه کوچک", sizeCm: 48.6, weightG: 2850, milestoneDe: "Das Baby gilt als termingerecht (voll entwickelt)", milestoneEn: "The baby is considered full-term", milestoneFa: "نوزاد کامل (ترم) محسوب می‌شود", tipDe: "Achte auf Anzeichen von Wehen – Kontraktionen, Wasserabgang", tipEn: "Watch for signs of labor – contractions, water breaking", tipFa: "به نشانه‌های زایمان توجه کن – انقباضات، شکستن آب" },
  { week: 38, fruit: "Rhabarber", fruitDe: "Rhabarber", fruitEn: "Rhubarb", fruitFa: "ریواس", sizeCm: 49.8, weightG: 3100, milestoneDe: "Das Baby verliert das Käseschmiermittel", milestoneEn: "The baby loses the vernix caseosa", milestoneFa: "نوزاد ورنیکس (چربی محافظ) را از دست می‌دهد", tipDe: "Ruhe bewahren – die meisten Babys kommen zwischen Woche 38-42", tipEn: "Stay calm – most babies arrive between weeks 38-42", tipFa: "آرام باش – بیشتر نوزادان بین هفته ۳۸-۴۲ به دنیا می‌آیند" },
  { week: 39, fruit: "Wassermelone", fruitDe: "Wassermelone", fruitEn: "Watermelon", fruitFa: "هندوانه", sizeCm: 50.7, weightG: 3250, milestoneDe: "Alle Organe sind bereit für das Leben außerhalb", milestoneEn: "All organs are ready for life outside", milestoneFa: "همه اندام‌ها برای زندگی خارج از رحم آماده هستند", tipDe: "Bald ist es so weit – genieße die letzten ruhigen Momente", tipEn: "Soon it's time – enjoy the last quiet moments", tipFa: "به زودی وقتش می‌رسد – از آخرین لحظات آرام لذت ببر" },
  { week: 40, fruit: "Wassermelone", fruitDe: "Wassermelone", fruitEn: "Watermelon", fruitFa: "هندوانه", sizeCm: 51, weightG: 3400, milestoneDe: "Herzlichen Glückwunsch – dein Baby ist bereit!", milestoneEn: "Congratulations – your baby is ready!", milestoneFa: "تبریک – نوزاد تو آماده است!", tipDe: "Du hast es geschafft! Alles Gute für die Geburt 💕", tipEn: "You did it! Best wishes for the birth 💕", tipFa: "انجامش دادی! بهترین آرزوها برای زایمان 💕" },
];

async function main() {
  for (const w of weeks) {
    await prisma.pregnancyWeek.upsert({
      where: { week: w.week },
      create: w,
      update: w,
    });
  }
  console.log(`Seeded ${weeks.length} pregnancy weeks.`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
